import React, { useMemo, useState } from "react";
import { seedDataService, SeedResult } from "./services/seedDataService";

const DEFAULT_DB_PROXY = "http://localhost:3011";

const formatSummary = (results: SeedResult[]) => {
  const allowed = results.filter((r) => r.policyDecision?.allowed).length;
  const blocked = results.length - allowed;
  return `Generated ${results.length} seeds. Allowed: ${allowed}. Blocked: ${blocked}.`;
};

export default function App() {
  const [apiKey, setApiKey] = useState(() => localStorage.getItem("pkg_seed_api_key") || "");
  const [count, setCount] = useState(4);
  const [dbProxyUrl, setDbProxyUrl] = useState(DEFAULT_DB_PROXY);
  const [includeKnowledge, setIncludeKnowledge] = useState(true);
  const [isRunning, setIsRunning] = useState(false);
  const [logs, setLogs] = useState<string[]>([]);
  const [results, setResults] = useState<SeedResult[]>([]);
  const summary = useMemo(() => (results.length ? formatSummary(results) : ""), [results]);

  const appendLog = (message: string) => {
    setLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] ${message}`]);
  };

  const handleGenerate = async () => {
    if (!apiKey || isRunning) return;
    setIsRunning(true);
    setResults([]);
    setLogs([]);
    localStorage.setItem("pkg_seed_api_key", apiKey);

    try {
      appendLog("Starting seed generation...");
      const generated = await seedDataService.generateSeeds({
        apiKey,
        count,
        dbProxyUrl,
        includeKnowledgeBase: includeKnowledge
      });
      setResults(generated);
      appendLog(`Seed generation complete (${generated.length} items).`);
    } catch (error: any) {
      appendLog(`Error: ${error.message || String(error)}`);
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <div className="page">
      <div className="container">
        <div className="header">
          <div>
            <p className="subtitle">PKG Simulator</p>
            <h1 className="title">Wearable Seed Generator</h1>
            <div className="badge">Gemini + Unified Memory</div>
          </div>
          <div className="field">
            <label>Gemini API Key</label>
            <input
              type="password"
              value={apiKey}
              onChange={(event) => setApiKey(event.target.value)}
              placeholder="Paste Gemini API Key"
            />
          </div>
        </div>

        <div className="card">
          <div className="grid">
            <div className="field">
              <label>Seed Count</label>
              <input
                type="number"
                min={1}
                max={10}
                value={count}
                onChange={(event) => setCount(Number(event.target.value))}
              />
            </div>
            <div className="field">
              <label>DB Proxy URL</label>
              <input
                value={dbProxyUrl}
                onChange={(event) => setDbProxyUrl(event.target.value)}
              />
            </div>
            <div className="field">
              <label>Knowledge Base Seed</label>
              <select
                value={includeKnowledge ? "yes" : "no"}
                onChange={(event) => setIncludeKnowledge(event.target.value === "yes")}
              >
                <option value="yes">Include approved tickets</option>
                <option value="no">Working memory only</option>
              </select>
            </div>
            <div className="field">
              <label>Notes</label>
              <textarea
                readOnly
                value="Seeds are generated by Gemini, evaluated by PKG policy, and appended to Unified Cortex memory."
              />
            </div>
          </div>

          <div className="actions">
            <button className="btn btn-primary" onClick={handleGenerate} disabled={!apiKey || isRunning}>
              {isRunning ? "Generating..." : "Generate Seeds"}
            </button>
          </div>

          {summary && <div className="summary">{summary}</div>}

          {logs.length > 0 && <div className="log">{logs.join("\n")}</div>}
        </div>
      </div>
    </div>
  );
}
